# Plugin List

# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Interactive command execution
[[plugins]] # Asynchronous
repo = 'Shougo/vimproc.vim'
build = 'make'

# Dark powered for interface
[[plugins]]
repo = 'Shougo/denite.nvim'

# Status bar
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Switch filetype by cursor position
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# File tree
[[plugins]]
repo = 'preservim/nerdtree'

# Asynchronous linting
[[plugins]]
repo = 'dense-analysis/ale'

# Language Server Protocol
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Snippet support
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# lexima
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# Hex editing
[[plugins]]
repo = 'Shougo/vinarise'

# Git
[[plugins]]
repo = "airblade/vim-gitgutter"
[[plugins]]
repo = 'tpope/vim-fugitive'

# Multiple cursor
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# Asynchronous completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# search and open file
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# Language
## go
[[plugins]]
repo = 'fatih/vim-go'
## html
[[plugins]]
repo = 'mattn/emmet-vim'

